### ISSUE TITLE
图片都不会显示

### ISSUE THREAD

**Issue by chenyang929** [qcrao/Go-Questions#14]
如题

**Comment by qcrao** [comment]
我这都可以显示。具体哪里不显示，发个链接出来吧。

**Comment by qcrao** [comment]
> 如题

我这都可以显示。具体哪里不显示，发个链接出来吧。

**Comment by qcrao** [comment]
需要科学上网~

**Comment by cquwb** [comment]
https://github.com/golang-design/Go-Questions/blob/master/content/sched/10-schedule%20%E5%BE%AA%E7%8E%AF%E5%A6%82%E4%BD%95%E5%90%AF%E5%8A%A8.md
这个里面有这样一张图片 路径好像是不存在的 我这也无法显示
https://github.com/golang-design/Go-Questions/blob/master/content/assets/0.png
