### ISSUE TITLE
数组和切片有什么异同.md这个里面给s2赋值100后,,打印s1并不会有100,图是不是画错了

### ISSUE THREAD

**Issue by 5201413** [qcrao/Go-Questions#18]
数组和切片有什么异同.md这个里面给s2赋值100后,,打印s1并不会有100,图是不是画错了

**Comment by qcrao** [comment]
> 数组和切片有什么异同.md这个里面给s2赋值100后,,打印s1并不会有100,图是不是画错了

没错。打印 s1，注意它的长度是  3。
