### ISSUE TITLE
【数组和切片】关于超过数组的上限赋值给新对象不会panic的讨论

### ISSUE THREAD

**Issue by Lvnszn** [qcrao/Go-Questions#20]
### 不会Panic的写法
```
testSlice := [...]int{1, 2}
newTestSlice := testSlice[2:]
for _, v := range newTestSlice {
	log.Print(v)
}
```

### 会Panic的写法
```
testSlice := [...]int{1, 2}
newTestSlice := testSlice[3:]
for _, v := range newTestSlice {
	log.Print(v)
}
```

output：
```
invalid slice index 3 (out of bounds for 2-element array)
```

直接取 **`testSlice[2]`** 也会报panic。

---

以上情况能加到数组和切片中去说明一下吗？

**Comment by qcrao** [comment]
> ### 不会Panic的写法
> ```
> testSlice := [...]int{1, 2}
> newTestSlice := testSlice[2:]
> for _, v := range newTestSlice {
> 	log.Print(v)
> }
> ```
> 
> ### 会Panic的写法
> ```
> testSlice := [...]int{1, 2}
> newTestSlice := testSlice[3:]
> for _, v := range newTestSlice {
> 	log.Print(v)
> }
> ```
> 
> output：
> 
> ```
> invalid slice index 3 (out of bounds for 2-element array)
> ```
> 
> 直接取 **`testSlice[2]`** 也会报panic。
> 
> 以上情况能加到数组和切片中去说明一下吗？

欢迎来提个 pr~
