### ISSUE TITLE
请问GC中如何看出来在3.75M开始触发垃圾回收的呢？

### ISSUE THREAD

**Issue by aioprxu** [qcrao/Go-Questions#8]
![image](https://user-images.githubusercontent.com/22276191/71477170-7deef480-2823-11ea-8714-18578a0b6eca.png)

**Comment by changkun** [comment]
你好，文中所表达的意思不是 GC 在 3.75M 开始触发，而是说：此时已经分配了 3.75M 内存，下一次产生内存分配时，GC 便被触发，符合图中观测。
